version: '3.8'
services:
  gateway:
    build: gateway
    image: gateway-image
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    image: server-image
    ports:
      - "9090:9090"