server:
  port: 8080
---
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:shareit
    password: test
    username: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
    open-in-view: false
    generate-ddl: on
  config:
    activate:
      on-profile: ci,test
  sql:
    init:
      mode: always
logging:
  level:
    org:
      springframework:
        orm:
          jpa:
            JpaTransactionManager: DEBUG
            nodeValue: INFO
        transaction:
          interceptor: TRACE
          nodeValue: INFO